/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export type DeploymentStruct = { name: string; addr: string };

export type DeploymentStructOutput = [string, string] & {
  name: string;
  addr: string;
};

export interface DeployPeripheryInterface extends utils.Interface {
  functions: {
    "IS_SCRIPT()": FunctionFragment;
    "deployCheckBalanceLow()": FunctionFragment;
    "deployCheckGelatoLow()": FunctionFragment;
    "deployCheckSecrets()": FunctionFragment;
    "deployCheckTrue()": FunctionFragment;
    "deployFaucet()": FunctionFragment;
    "deployFaucetDrippie()": FunctionFragment;
    "deployFaucetProxy()": FunctionFragment;
    "deployOffChainAuthModule()": FunctionFragment;
    "deployOnChainAuthModule()": FunctionFragment;
    "deployOperationsDrippie()": FunctionFragment;
    "deployProxyAdmin()": FunctionFragment;
    "get(string)": FunctionFragment;
    "getAddress(string)": FunctionFragment;
    "has(string)": FunctionFragment;
    "initializeFaucet()": FunctionFragment;
    "installFaucetAuthModulesConfigs()": FunctionFragment;
    "installOffChainAuthModule()": FunctionFragment;
    "installOnChainAuthModule()": FunctionFragment;
    "loadInitializedSlot(string)": FunctionFragment;
    "mustGetAddress(string)": FunctionFragment;
    "newDeployments()": FunctionFragment;
    "prankDeployment(string,address)": FunctionFragment;
    "run()": FunctionFragment;
    "save(string,address)": FunctionFragment;
    "setUp()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "IS_SCRIPT"
      | "deployCheckBalanceLow"
      | "deployCheckGelatoLow"
      | "deployCheckSecrets"
      | "deployCheckTrue"
      | "deployFaucet"
      | "deployFaucetDrippie"
      | "deployFaucetProxy"
      | "deployOffChainAuthModule"
      | "deployOnChainAuthModule"
      | "deployOperationsDrippie"
      | "deployProxyAdmin"
      | "get"
      | "getAddress"
      | "has"
      | "initializeFaucet"
      | "installFaucetAuthModulesConfigs"
      | "installOffChainAuthModule"
      | "installOnChainAuthModule"
      | "loadInitializedSlot"
      | "mustGetAddress"
      | "newDeployments"
      | "prankDeployment"
      | "run"
      | "save"
      | "setUp"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "IS_SCRIPT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deployCheckBalanceLow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployCheckGelatoLow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployCheckSecrets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployCheckTrue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployFaucet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployFaucetDrippie",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployFaucetProxy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployOffChainAuthModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployOnChainAuthModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployOperationsDrippie",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployProxyAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "get", values: [string]): string;
  encodeFunctionData(functionFragment: "getAddress", values: [string]): string;
  encodeFunctionData(functionFragment: "has", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initializeFaucet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "installFaucetAuthModulesConfigs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "installOffChainAuthModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "installOnChainAuthModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "loadInitializedSlot",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mustGetAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "newDeployments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "prankDeployment",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "run", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "save",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;

  decodeFunctionResult(functionFragment: "IS_SCRIPT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployCheckBalanceLow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployCheckGelatoLow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployCheckSecrets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployCheckTrue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployFaucet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployFaucetDrippie",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployFaucetProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployOffChainAuthModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployOnChainAuthModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployOperationsDrippie",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployProxyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "has", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeFaucet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installFaucetAuthModulesConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installOffChainAuthModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installOnChainAuthModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loadInitializedSlot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mustGetAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newDeployments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prankDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "save", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;

  events: {};
}

export interface DeployPeriphery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeployPeripheryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<[boolean]>;

    /**
     * Deploy CheckBalanceLow contract.
     */
    deployCheckBalanceLow(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy CheckGelatoLow contract.
     */
    deployCheckGelatoLow(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy CheckSecrets contract.
     */
    deployCheckSecrets(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy CheckTrue contract.
     */
    deployCheckTrue(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy the Faucet contract.
     */
    deployFaucet(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy the Drippie contract.
     */
    deployFaucetDrippie(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy FaucetProxy.
     */
    deployFaucetProxy(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy Off-Chain Authentication Module.
     */
    deployOffChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy On-Chain Authentication Module.
     */
    deployOnChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy the Drippie contract for standard operations.
     */
    deployOperationsDrippie(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy ProxyAdmin.
     */
    deployProxyAdmin(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Returns a deployment that is suitable to be used to interact with contracts.
     * @param _name The name of the deployment.
     */
    get(
      _name: string,
      overrides?: CallOverrides
    ): Promise<[DeploymentStructOutput]>;

    /**
     * Returns the address of a deployment. Also handles the predeploys.
     * @param _name The name of the deployment.
     */
    getAddress(_name: string, overrides?: CallOverrides): Promise<[string]>;

    /**
     * Returns whether or not a particular deployment exists.
     * @param _name The name of the deployment.
     */
    has(_name: string, overrides?: CallOverrides): Promise<[boolean]>;

    /**
     * Initialize the Faucet.
     */
    initializeFaucet(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Installs all of the auth modules in the faucet contract.
     */
    installFaucetAuthModulesConfigs(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Installs the OffChain AuthModule on the Faucet contract.
     */
    installOffChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Installs the OnChain AuthModule on the Faucet contract.
     */
    installOnChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Returns the value of the internal `_initialized` storage slot for a given contract.
     */
    loadInitializedSlot(
      _contractName: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Returns the address of a deployment and reverts if the deployment         does not exist.
     */
    mustGetAddress(_name: string, overrides?: CallOverrides): Promise<[string]>;

    /**
     * Returns all of the deployments done in the current context.
     */
    newDeployments(
      overrides?: CallOverrides
    ): Promise<[DeploymentStructOutput[]]>;

    /**
     * Stubs a deployment retrieved through `get`.
     * @param _addr The mock address of the deployment.
     * @param _name The name of the deployment.
     */
    prankDeployment(
      _name: string,
      _addr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Deploy all of the periphery contracts.
     */
    run(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Appends a deployment to disk as a JSON deploy artifact.
     * @param _deployed The address of the deployment.
     * @param _name The name of the deployment.
     */
    save(
      _name: string,
      _deployed: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Sets up the deployment script.
     */
    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

  /**
   * Deploy CheckBalanceLow contract.
   */
  deployCheckBalanceLow(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy CheckGelatoLow contract.
   */
  deployCheckGelatoLow(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy CheckSecrets contract.
   */
  deployCheckSecrets(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy CheckTrue contract.
   */
  deployCheckTrue(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy the Faucet contract.
   */
  deployFaucet(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy the Drippie contract.
   */
  deployFaucetDrippie(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy FaucetProxy.
   */
  deployFaucetProxy(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy Off-Chain Authentication Module.
   */
  deployOffChainAuthModule(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy On-Chain Authentication Module.
   */
  deployOnChainAuthModule(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy the Drippie contract for standard operations.
   */
  deployOperationsDrippie(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy ProxyAdmin.
   */
  deployProxyAdmin(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Returns a deployment that is suitable to be used to interact with contracts.
   * @param _name The name of the deployment.
   */
  get(
    _name: string,
    overrides?: CallOverrides
  ): Promise<DeploymentStructOutput>;

  /**
   * Returns the address of a deployment. Also handles the predeploys.
   * @param _name The name of the deployment.
   */
  getAddress(_name: string, overrides?: CallOverrides): Promise<string>;

  /**
   * Returns whether or not a particular deployment exists.
   * @param _name The name of the deployment.
   */
  has(_name: string, overrides?: CallOverrides): Promise<boolean>;

  /**
   * Initialize the Faucet.
   */
  initializeFaucet(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Installs all of the auth modules in the faucet contract.
   */
  installFaucetAuthModulesConfigs(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Installs the OffChain AuthModule on the Faucet contract.
   */
  installOffChainAuthModule(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Installs the OnChain AuthModule on the Faucet contract.
   */
  installOnChainAuthModule(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Returns the value of the internal `_initialized` storage slot for a given contract.
   */
  loadInitializedSlot(
    _contractName: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Returns the address of a deployment and reverts if the deployment         does not exist.
   */
  mustGetAddress(_name: string, overrides?: CallOverrides): Promise<string>;

  /**
   * Returns all of the deployments done in the current context.
   */
  newDeployments(overrides?: CallOverrides): Promise<DeploymentStructOutput[]>;

  /**
   * Stubs a deployment retrieved through `get`.
   * @param _addr The mock address of the deployment.
   * @param _name The name of the deployment.
   */
  prankDeployment(
    _name: string,
    _addr: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Deploy all of the periphery contracts.
   */
  run(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>;

  /**
   * Appends a deployment to disk as a JSON deploy artifact.
   * @param _deployed The address of the deployment.
   * @param _name The name of the deployment.
   */
  save(
    _name: string,
    _deployed: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Sets up the deployment script.
   */
  setUp(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<boolean>;

    /**
     * Deploy CheckBalanceLow contract.
     */
    deployCheckBalanceLow(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy CheckGelatoLow contract.
     */
    deployCheckGelatoLow(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy CheckSecrets contract.
     */
    deployCheckSecrets(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy CheckTrue contract.
     */
    deployCheckTrue(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy the Faucet contract.
     */
    deployFaucet(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy the Drippie contract.
     */
    deployFaucetDrippie(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy FaucetProxy.
     */
    deployFaucetProxy(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy Off-Chain Authentication Module.
     */
    deployOffChainAuthModule(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy On-Chain Authentication Module.
     */
    deployOnChainAuthModule(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy the Drippie contract for standard operations.
     */
    deployOperationsDrippie(overrides?: CallOverrides): Promise<string>;

    /**
     * Deploy ProxyAdmin.
     */
    deployProxyAdmin(overrides?: CallOverrides): Promise<string>;

    /**
     * Returns a deployment that is suitable to be used to interact with contracts.
     * @param _name The name of the deployment.
     */
    get(
      _name: string,
      overrides?: CallOverrides
    ): Promise<DeploymentStructOutput>;

    /**
     * Returns the address of a deployment. Also handles the predeploys.
     * @param _name The name of the deployment.
     */
    getAddress(_name: string, overrides?: CallOverrides): Promise<string>;

    /**
     * Returns whether or not a particular deployment exists.
     * @param _name The name of the deployment.
     */
    has(_name: string, overrides?: CallOverrides): Promise<boolean>;

    /**
     * Initialize the Faucet.
     */
    initializeFaucet(overrides?: CallOverrides): Promise<void>;

    /**
     * Installs all of the auth modules in the faucet contract.
     */
    installFaucetAuthModulesConfigs(overrides?: CallOverrides): Promise<void>;

    /**
     * Installs the OffChain AuthModule on the Faucet contract.
     */
    installOffChainAuthModule(overrides?: CallOverrides): Promise<void>;

    /**
     * Installs the OnChain AuthModule on the Faucet contract.
     */
    installOnChainAuthModule(overrides?: CallOverrides): Promise<void>;

    /**
     * Returns the value of the internal `_initialized` storage slot for a given contract.
     */
    loadInitializedSlot(
      _contractName: string,
      overrides?: CallOverrides
    ): Promise<number>;

    /**
     * Returns the address of a deployment and reverts if the deployment         does not exist.
     */
    mustGetAddress(_name: string, overrides?: CallOverrides): Promise<string>;

    /**
     * Returns all of the deployments done in the current context.
     */
    newDeployments(
      overrides?: CallOverrides
    ): Promise<DeploymentStructOutput[]>;

    /**
     * Stubs a deployment retrieved through `get`.
     * @param _addr The mock address of the deployment.
     * @param _name The name of the deployment.
     */
    prankDeployment(
      _name: string,
      _addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Deploy all of the periphery contracts.
     */
    run(overrides?: CallOverrides): Promise<void>;

    /**
     * Appends a deployment to disk as a JSON deploy artifact.
     * @param _deployed The address of the deployment.
     * @param _name The name of the deployment.
     */
    save(
      _name: string,
      _deployed: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Sets up the deployment script.
     */
    setUp(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Deploy CheckBalanceLow contract.
     */
    deployCheckBalanceLow(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy CheckGelatoLow contract.
     */
    deployCheckGelatoLow(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy CheckSecrets contract.
     */
    deployCheckSecrets(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy CheckTrue contract.
     */
    deployCheckTrue(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy the Faucet contract.
     */
    deployFaucet(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    /**
     * Deploy the Drippie contract.
     */
    deployFaucetDrippie(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy FaucetProxy.
     */
    deployFaucetProxy(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy Off-Chain Authentication Module.
     */
    deployOffChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy On-Chain Authentication Module.
     */
    deployOnChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy the Drippie contract for standard operations.
     */
    deployOperationsDrippie(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy ProxyAdmin.
     */
    deployProxyAdmin(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Returns a deployment that is suitable to be used to interact with contracts.
     * @param _name The name of the deployment.
     */
    get(_name: string, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns the address of a deployment. Also handles the predeploys.
     * @param _name The name of the deployment.
     */
    getAddress(_name: string, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Returns whether or not a particular deployment exists.
     * @param _name The name of the deployment.
     */
    has(_name: string, overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Initialize the Faucet.
     */
    initializeFaucet(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Installs all of the auth modules in the faucet contract.
     */
    installFaucetAuthModulesConfigs(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Installs the OffChain AuthModule on the Faucet contract.
     */
    installOffChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Installs the OnChain AuthModule on the Faucet contract.
     */
    installOnChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Returns the value of the internal `_initialized` storage slot for a given contract.
     */
    loadInitializedSlot(
      _contractName: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Returns the address of a deployment and reverts if the deployment         does not exist.
     */
    mustGetAddress(
      _name: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns all of the deployments done in the current context.
     */
    newDeployments(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Stubs a deployment retrieved through `get`.
     * @param _addr The mock address of the deployment.
     * @param _name The name of the deployment.
     */
    prankDeployment(
      _name: string,
      _addr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Deploy all of the periphery contracts.
     */
    run(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    /**
     * Appends a deployment to disk as a JSON deploy artifact.
     * @param _deployed The address of the deployment.
     * @param _name The name of the deployment.
     */
    save(
      _name: string,
      _deployed: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Sets up the deployment script.
     */
    setUp(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_SCRIPT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Deploy CheckBalanceLow contract.
     */
    deployCheckBalanceLow(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy CheckGelatoLow contract.
     */
    deployCheckGelatoLow(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy CheckSecrets contract.
     */
    deployCheckSecrets(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy CheckTrue contract.
     */
    deployCheckTrue(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy the Faucet contract.
     */
    deployFaucet(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy the Drippie contract.
     */
    deployFaucetDrippie(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy FaucetProxy.
     */
    deployFaucetProxy(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy Off-Chain Authentication Module.
     */
    deployOffChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy On-Chain Authentication Module.
     */
    deployOnChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy the Drippie contract for standard operations.
     */
    deployOperationsDrippie(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy ProxyAdmin.
     */
    deployProxyAdmin(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns a deployment that is suitable to be used to interact with contracts.
     * @param _name The name of the deployment.
     */
    get(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the address of a deployment. Also handles the predeploys.
     * @param _name The name of the deployment.
     */
    getAddress(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns whether or not a particular deployment exists.
     * @param _name The name of the deployment.
     */
    has(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Initialize the Faucet.
     */
    initializeFaucet(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Installs all of the auth modules in the faucet contract.
     */
    installFaucetAuthModulesConfigs(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Installs the OffChain AuthModule on the Faucet contract.
     */
    installOffChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Installs the OnChain AuthModule on the Faucet contract.
     */
    installOnChainAuthModule(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the value of the internal `_initialized` storage slot for a given contract.
     */
    loadInitializedSlot(
      _contractName: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the address of a deployment and reverts if the deployment         does not exist.
     */
    mustGetAddress(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns all of the deployments done in the current context.
     */
    newDeployments(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Stubs a deployment retrieved through `get`.
     * @param _addr The mock address of the deployment.
     * @param _name The name of the deployment.
     */
    prankDeployment(
      _name: string,
      _addr: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Deploy all of the periphery contracts.
     */
    run(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Appends a deployment to disk as a JSON deploy artifact.
     * @param _deployed The address of the deployment.
     * @param _name The name of the deployment.
     */
    save(
      _name: string,
      _deployed: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Sets up the deployment script.
     */
    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
