/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInitializable0815,
  IInitializable0815Interface,
} from "../../IInitializable.sol/IInitializable0815";

const _abi = [
  {
    type: "function",
    name: "initialize",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
] as const;

export class IInitializable0815__factory {
  static readonly abi = _abi;
  static createInterface(): IInitializable0815Interface {
    return new utils.Interface(_abi) as IInitializable0815Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInitializable0815 {
    return new Contract(address, _abi, signerOrProvider) as IInitializable0815;
  }
}
