/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGelatoTreasury,
  IGelatoTreasuryInterface,
} from "../../CheckGelatoLow.sol/IGelatoTreasury";

const _abi = [
  {
    type: "function",
    name: "totalDepositedAmount",
    inputs: [
      {
        name: "_user",
        type: "address",
        internalType: "address",
      },
      {
        name: "_token",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalWithdrawnAmount",
    inputs: [
      {
        name: "_user",
        type: "address",
        internalType: "address",
      },
      {
        name: "_token",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IGelatoTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): IGelatoTreasuryInterface {
    return new utils.Interface(_abi) as IGelatoTreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGelatoTreasury {
    return new Contract(address, _abi, signerOrProvider) as IGelatoTreasury;
  }
}
