/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { IERC1650815 } from "./IERC1650815";
export type { IERC1650825 } from "./IERC1650825";
