/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SafeSend0825,
  SafeSend0825Interface,
} from "../../SafeSend.sol/SafeSend0825";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_recipient",
        type: "address",
        internalType: "address payable",
      },
    ],
    stateMutability: "payable",
  },
] as const;

const _bytecode =
  "0x608060405260405160563803806056833981016040819052601e91602a565b806001600160a01b0316ff5b5f602082840312156039575f80fd5b81516001600160a01b0381168114604e575f80fd5b939250505056fe";

type SafeSend0825ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SafeSend0825ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SafeSend0825__factory extends ContractFactory {
  constructor(...args: SafeSend0825ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _recipient: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<SafeSend0825> {
    return super.deploy(_recipient, overrides || {}) as Promise<SafeSend0825>;
  }
  override getDeployTransaction(
    _recipient: string,
    overrides?: PayableOverrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(_recipient, overrides || {});
  }
  override attach(address: string): SafeSend0825 {
    return super.attach(address) as SafeSend0825;
  }
  override connect(signer: Signer): SafeSend0825__factory {
    return super.connect(signer) as SafeSend0825__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SafeSend0825Interface {
    return new utils.Interface(_abi) as SafeSend0825Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeSend0825 {
    return new Contract(address, _abi, signerOrProvider) as SafeSend0825;
  }
}
