/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface MIPS2Interface extends utils.Interface {
  functions: {
    "step(bytes,bytes,bytes32)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "step" | "version"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "step",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "step", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {};
}

export interface MIPS2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MIPS2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Executes a single step of the multi-threaded vm.         Will revert if any required input state is missing.
     * @param _localContext The local key context for the preimage oracle. Optional, can be set as a constant                      if the caller only requires one set of local keys.
     * @param _proof The encoded proof data: <<thread_context, inner_root>, <memory proof>.               Contains the thread context witness and the memory proof data for leaves within the MIPS VM's memory.               The thread context witness is a packed tuple of the thread context and the immediate inner root of the current thread stack.
     * @param _stateData The encoded state witness data.
     */
    step(
      _stateData: BytesLike,
      _proof: BytesLike,
      _localContext: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * The semantic version of the MIPS2 contract.
     */
    version(overrides?: CallOverrides): Promise<[string]>;
  };

  /**
   * Executes a single step of the multi-threaded vm.         Will revert if any required input state is missing.
   * @param _localContext The local key context for the preimage oracle. Optional, can be set as a constant                      if the caller only requires one set of local keys.
   * @param _proof The encoded proof data: <<thread_context, inner_root>, <memory proof>.               Contains the thread context witness and the memory proof data for leaves within the MIPS VM's memory.               The thread context witness is a packed tuple of the thread context and the immediate inner root of the current thread stack.
   * @param _stateData The encoded state witness data.
   */
  step(
    _stateData: BytesLike,
    _proof: BytesLike,
    _localContext: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * The semantic version of the MIPS2 contract.
   */
  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    /**
     * Executes a single step of the multi-threaded vm.         Will revert if any required input state is missing.
     * @param _localContext The local key context for the preimage oracle. Optional, can be set as a constant                      if the caller only requires one set of local keys.
     * @param _proof The encoded proof data: <<thread_context, inner_root>, <memory proof>.               Contains the thread context witness and the memory proof data for leaves within the MIPS VM's memory.               The thread context witness is a packed tuple of the thread context and the immediate inner root of the current thread stack.
     * @param _stateData The encoded state witness data.
     */
    step(
      _stateData: BytesLike,
      _proof: BytesLike,
      _localContext: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * The semantic version of the MIPS2 contract.
     */
    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    /**
     * Executes a single step of the multi-threaded vm.         Will revert if any required input state is missing.
     * @param _localContext The local key context for the preimage oracle. Optional, can be set as a constant                      if the caller only requires one set of local keys.
     * @param _proof The encoded proof data: <<thread_context, inner_root>, <memory proof>.               Contains the thread context witness and the memory proof data for leaves within the MIPS VM's memory.               The thread context witness is a packed tuple of the thread context and the immediate inner root of the current thread stack.
     * @param _stateData The encoded state witness data.
     */
    step(
      _stateData: BytesLike,
      _proof: BytesLike,
      _localContext: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * The semantic version of the MIPS2 contract.
     */
    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Executes a single step of the multi-threaded vm.         Will revert if any required input state is missing.
     * @param _localContext The local key context for the preimage oracle. Optional, can be set as a constant                      if the caller only requires one set of local keys.
     * @param _proof The encoded proof data: <<thread_context, inner_root>, <memory proof>.               Contains the thread context witness and the memory proof data for leaves within the MIPS VM's memory.               The thread context witness is a packed tuple of the thread context and the immediate inner root of the current thread stack.
     * @param _stateData The encoded state witness data.
     */
    step(
      _stateData: BytesLike,
      _proof: BytesLike,
      _localContext: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * The semantic version of the MIPS2 contract.
     */
    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
