/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ERC721TokenReceiver0815,
  ERC721TokenReceiver0815Interface,
} from "../../ERC721.sol/ERC721TokenReceiver0815";

const _abi = [
  {
    type: "function",
    name: "onERC721Received",
    inputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class ERC721TokenReceiver0815__factory {
  static readonly abi = _abi;
  static createInterface(): ERC721TokenReceiver0815Interface {
    return new utils.Interface(_abi) as ERC721TokenReceiver0815Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC721TokenReceiver0815 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC721TokenReceiver0815;
  }
}
